# Generated by Django 6.0.5 on 2026-05-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('borrow_request', 'Borrow Request'), ('borrow_approved', 'Borrow Approved'), ('borrow_rejected', 'Borrow Rejected'), ('book_returned', 'Book Returned'), ('review_created', 'Review Created'), ('review_updated', 'Review Updated'), ('review_deleted', 'Review Deleted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
